In [19]:
# importing the tf guys
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout,LSTM
from tensorflow.keras.utils import plot_model

# tool for manipulate the data
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [20]:
X, y = load_iris(as_frame=True, return_X_y=True)

In [21]:
X.sample(5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
80,5.5,2.4,3.8,1.1
90,5.5,2.6,4.4,1.2
31,5.4,3.4,1.5,0.4
89,5.5,2.5,4.0,1.3
133,6.3,2.8,5.1,1.5


In [22]:
y.sample(5)

45     0
76     1
127    2
111    2
95     1
Name: target, dtype: int64

In [23]:
# splitting the data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [24]:
model = Sequential([
    Dense(
        units=50,
        input_shape=(X_train.shape[1],),
        activation="relu",
        kernel_initializer='uniform',
    ),
    Dropout(0.25),
    Dense(
        units=4,
        activation="relu",
        kernel_initializer='uniform',
    ),
    Dense(
        units=3,
        activation="softmax",
        kernel_initializer='uniform',
    )
])

model.summary()

C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                      │ (None, 50)                  │             250 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 50)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 4)                   │             204 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 3)                   │              15 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 469 (1.83 KB)

 Trainable params: 469 (1.83 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
plot_model(model)

You must install graphviz (see instructions at https://graphviz.gitlab.io/download/) for `plot_model` to work.


In [26]:
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

In [27]:
model.fit(
    X_train,
    y_train,
    epochs=100,
    verbose=True,
)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.2869 - loss: 1.0986  
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3308 - loss: 1.0983 
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4933 - loss: 1.0979 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6348 - loss: 1.0973 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6579 - loss: 1.0965 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6633 - loss: 1.0956 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6323 - loss: 1.0944
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6610 - loss: 1.0929
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5806 - loss: 1.0909 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6092 - loss: 1.0880 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6046 - loss: 1.0848 
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6221 - l

In [28]:
predictions = model.predict(X_test[:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


In [29]:
import numpy as np
print("Predictions (probabilities):", predictions)
print("Predicted Classes:", np.argmax(predictions, axis=1))
print("True Classes:", np.argmax(y_test[:5], axis=0))

Predictions (probabilities): [[4.9144635e-03 6.3774991e-01 3.5733563e-01]
 [5.6568189e-03 6.0446072e-01 3.8988242e-01]
 [3.0989526e-04 4.1200435e-01 5.8768576e-01]
 [1.6995043e-02 7.0479894e-01 2.7820602e-01]
 [1.3094057e-06 1.5830173e-01 8.4169698e-01]]
Predicted Classes: [1 1 2 1 2]
True Classes: 2
