In [2]:
import tensorflow as tf

# Constant tensor
tensor_a = tf.constant([1, 2, 3])
print("Constant Tensor:", tensor_a)

# Random tensor
tensor_b = tf.random.normal([2, 3])
print("Random Tensor:\n", tensor_b)

# Zero tensor
tensor_c = tf.zeros([2, 2])
print("Zero Tensor:\n", tensor_c)


Constant Tensor: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Random Tensor:
 tf.Tensor(
[[-0.5049563 -1.5276684 -0.8412157]
 [ 0.0991171  1.0585544 -1.4307307]], shape=(2, 3), dtype=float32)
Zero Tensor:
 tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [7]:
import tensorflow as tf
import numpy as np

# Define matrices
matrix1 = np.array([(2, 2, 2), (2, 2, 2), (2, 2, 2)], dtype='int32')
matrix2 = np.array([(1, 1, 1), (1, 1, 1), (1, 1, 1)], dtype='int32')

print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)

# Convert matrices to TensorFlow constants
matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)

# TensorFlow operations
matrix_product = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1, matrix2)

# Define a third matrix for determinant calculation
matrix_3 = np.array([(2, 7, 2), (1, 4, 2), (9, 0, 2)], dtype='float32')
print("Matrix 3:")
print(matrix_3)

# Calculate determinant
matrix_det = tf.linalg.det(matrix_3)

# Display results
print("\nMatrix Product:")
print(matrix_product.numpy())

print("\nMatrix Sum:")
print(matrix_sum.numpy())

print("\nDeterminant of Matrix 3:")
print(matrix_det.numpy())


Matrix 1:
[[2 2 2]
 [2 2 2]
 [2 2 2]]
Matrix 2:
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Matrix 3:
[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]

Matrix Product:
[[6 6 6]
 [6 6 6]
 [6 6 6]]

Matrix Sum:
[[3 3 3]
 [3 3 3]
 [3 3 3]]

Determinant of Matrix 3:
55.999992


In [3]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
result = tf.add(a, b)
print("Addition:", result)


Addition: tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [4]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
result = tf.matmul(a, b)
print("Matrix Multiplication:\n", result)


Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [5]:
import tensorflow as tf

# Data
X = tf.constant([1.0, 2.0, 3.0, 4.0], dtype=tf.float32)
y = tf.constant([5.0, 8.0, 11.0, 14.0], dtype=tf.float32)

# Variables
W = tf.Variable(0.0)
b = tf.Variable(0.0)

# Model
def linear_model(X):
    return W * X + b

# Loss function (Mean Squared Error)
def loss_fn(y_true, y_pred):
    return tf.reduce_mean(tf.square(y_true - y_pred))

# Optimizer
optimizer = tf.optimizers.Adam(learning_rate=0.1)

# Training
for epoch in range(100):
    with tf.GradientTape() as tape:
        predictions = linear_model(X)
        loss = loss_fn(y, predictions)
    gradients = tape.gradient(loss, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))

    if epoch % 10 == 0:
        print(f"Epoch {epoch}: Loss = {loss.numpy()}, W = {W.numpy()}, b = {b.numpy()}")

print(f"Final Model: y = {W.numpy()}x + {b.numpy()}")


Epoch 0: Loss = 101.5, W = 0.0999993309378624, b = 0.0999993160367012
Epoch 10: Loss = 41.75373840332031, W = 1.0787488222122192, b = 1.0783706903457642
Epoch 20: Loss = 10.473135948181152, W = 1.9421868324279785, b = 1.938906192779541
Epoch 30: Loss = 0.7622304558753967, W = 2.569944381713867, b = 2.5574259757995605
Epoch 40: Loss = 0.29704317450523376, W = 2.891523599624634, b = 2.860551118850708
Epoch 50: Loss = 0.6152361631393433, W = 2.951080322265625, b = 2.8934929370880127
Epoch 60: Loss = 0.28221458196640015, W = 2.8765106201171875, b = 2.7876205444335938
Epoch 70: Loss = 0.08086954057216644, W = 2.790393114089966, b = 2.6684186458587646
Epoch 80: Loss = 0.07561208307743073, W = 2.753049850463867, b = 2.5976595878601074
Epoch 90: Loss = 0.07234227657318115, W = 2.762672185897827, b = 2.5738208293914795
Final Model: y = 2.787210464477539x + 2.5680060386657715


In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Data
X = np.random.rand(1000, 2)
y = np.array([1 if x[0] + x[1] > 1 else 0 for x in X])

# Model
model = Sequential([
    Dense(16, activation='relu', input_shape=(2,)),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train
model.fit(X, y, epochs=10, batch_size=32)

# Predict
print("Predictions:", model.predict(X[:5]))


C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.5586 - loss: 0.6586
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5411 - loss: 0.6351
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6338 - loss: 0.6050
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7138 - loss: 0.5764
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7749 - loss: 0.5428
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8448 - loss: 0.4984
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8685 - loss: 0.4487
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8975 - loss: 0.4022
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9327 - loss: 0.3597
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9205 - loss: 0.3278
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step
Predictions: [[0.9404799 ]
 [0.8017668 ]
 [0.20148994]
 [0.18163197]
 [0.89683264]]


In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM#, CuDNNLSTM


mnist = tf.keras.datasets.mnist  # mnist is a dataset of 28x28 images of handwritten digits and their labels
(x_train, y_train),(x_test, y_test) = mnist.load_data()  # unpacks images to x_train/x_test and labels to y_train/y_test

x_train = x_train/255.0
x_test = x_test/255.0

print(x_train.shape)
print(x_train[0].shape)

model = Sequential()

# IF you are running with a GPU, try out the CuDNNLSTM layer type instead (don't pass an activation, tanh is required)
model.add(LSTM(128, input_shape=(x_train.shape[1:]), activation='relu', return_sequences=True))
model.add(Dropout(0.2))

model.add(LSTM(128, activation='relu'))
model.add(Dropout(0.1))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(10, activation='softmax'))

opt = tf.keras.optimizers.Adam(learning_rate=0.001, decay=1e-6)

# Compile model
model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer=opt,
    metrics=['accuracy'],
)

model.fit(x_train,
          y_train,
          epochs=3,
          validation_data=(x_test, y_test))

(60000, 28, 28)
(28, 28)
Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 95s 49ms/step - accuracy: 0.6225 - loss: 1.0825 - val_accuracy: 0.9662 - val_loss: 0.1144
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 86s 46ms/step - accuracy: 0.9548 - loss: 0.1625 - val_accuracy: 0.9727 - val_loss: 0.0933
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 85s 45ms/step - accuracy: 0.9693 - loss: 0.1111 - val_accuracy: 0.9814 - val_loss: 0.0624


In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, SimpleRNN

# Load MNIST dataset
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize the data
x_train = x_train / 255.0
x_test = x_test / 255.0

print(x_train.shape)
print(x_train[0].shape)

# Build the RNN model
model = Sequential()

# Add a SimpleRNN layer
model.add(SimpleRNN(128, input_shape=(x_train.shape[1:]), activation='relu', return_sequences=True))
model.add(Dropout(0.2))

# Add another SimpleRNN layer
model.add(SimpleRNN(128, activation='relu'))
model.add(Dropout(0.1))

# Add a fully connected Dense layer
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

# Output layer with 10 units (one for each digit, 0-9)
model.add(Dense(10, activation='softmax'))

# Compile the model
opt = tf.keras.optimizers.Adam(learning_rate=0.001, decay=1e-6)

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer=opt,
    metrics=['accuracy'],
)

# Train the model
model.fit(x_train, y_train, epochs=3, validation_data=(x_test, y_test))


(60000, 28, 28)
(28, 28)
Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 26s 13ms/step - accuracy: 0.7008 - loss: 0.8945 - val_accuracy: 0.9394 - val_loss: 0.2192
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 31s 17ms/step - accuracy: 0.9361 - loss: 0.2408 - val_accuracy: 0.9578 - val_loss: 0.1531
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 28s 15ms/step - accuracy: 0.9562 - loss: 0.1737 - val_accuracy: 0.9594 - val_loss: 0.1381
